<?php

namespace Database\Seeders;

use App\Models\DataPlan;
use Illuminate\Database\Seeder;

class SmileDataPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataplans = [
            [
                'planid' => '758',
                'name' => 'Freedom Mobile Plan for 30days - 5,000 Naira',
                'price' => '5000.00',
                'userprice' => '5000.00',
                'agentprice' => '5000.00',
                'vendorprice' => '5000.00',
                'day' => '30',
                'type' => 'SME', // Assuming SME for data type based on controller check
                'datanetwork' => 5, // Smile
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '843',
                'name' => 'SmileMINI 1GB for 1days - 450 Naira',
                'price' => '450.00',
                'userprice' => '450.00',
                'agentprice' => '450.00',
                'vendorprice' => '450.00',
                'day' => '1',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '844',
                'name' => 'Smile MINI 2.5GB for 1days - 750 Naira',
                'price' => '750.00',
                'userprice' => '750.00',
                'agentprice' => '750.00',
                'vendorprice' => '750.00',
                'day' => '1',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '847',
                'name' => 'Smile MINI 1GB for 7days - 750 Naira',
                'price' => '750.00',
                'userprice' => '750.00',
                'agentprice' => '750.00',
                'vendorprice' => '750.00',
                'day' => '7',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '803',
                'name' => 'SmileVoice ONLY 65 for 30days - 900 Naira',
                'price' => '900.00',
                'userprice' => '900.00',
                'agentprice' => '900.00',
                'vendorprice' => '900.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '828',
                'name' => 'Smile MIDI 1.5GB for 30days - 1,250 Naira',
                'price' => '1250.00',
                'userprice' => '1250.00',
                'agentprice' => '1250.00',
                'vendorprice' => '1250.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '829',
                'name' => 'Smile MIDI 2GB for 30days - 1,500 Naira',
                'price' => '1500.00',
                'userprice' => '1500.00',
                'agentprice' => '1500.00',
                'vendorprice' => '1500.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '845',
                'name' => 'Smile MINI 3GB for 2days - 1,500 Naira',
                'price' => '1500.00',
                'userprice' => '1500.00',
                'agentprice' => '1500.00',
                'vendorprice' => '1500.00',
                'day' => '2',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '848',
                'name' => 'Smile MINI 3.5GB for 7days - 1,500 Naira',
                'price' => '1500.00',
                'userprice' => '1500.00',
                'agentprice' => '1500.00',
                'vendorprice' => '1500.00',
                'day' => '7',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '804',
                'name' => 'SmileVoice ONLY 135 for 30days - 1,850 Naira',
                'price' => '1850.00',
                'userprice' => '1850.00',
                'agentprice' => '1850.00',
                'vendorprice' => '1850.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '830',
                'name' => 'Smile MIDI 3GB for 30days - 2,000 Naira',
                'price' => '2000.00',
                'userprice' => '2000.00',
                'agentprice' => '2000.00',
                'vendorprice' => '2000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '846',
                'name' => 'Smile MINI 5GB for 2days - 2,200 Naira',
                'price' => '2200.00',
                'userprice' => '2200.00',
                'agentprice' => '2200.00',
                'vendorprice' => '2200.00',
                'day' => '2',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '849',
                'name' => 'Smile MINI 6GB for 7days - 2,300 Naira',
                'price' => '2300.00',
                'userprice' => '2300.00',
                'agentprice' => '2300.00',
                'vendorprice' => '2300.00',
                'day' => '7',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '806',
                'name' => 'SmileVoice ONLY 150 for 60days - 2,700 Naira',
                'price' => '2700.00',
                'userprice' => '2700.00',
                'agentprice' => '2700.00',
                'vendorprice' => '2700.00',
                'day' => '60',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '831',
                'name' => 'Smile MIDI 6GB for 30days - 3,000 Naira',
                'price' => '3000.00',
                'userprice' => '3000.00',
                'agentprice' => '3000.00',
                'vendorprice' => '3000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '832',
                'name' => 'Smile MIDI 8GB for 30days - 3,500 Naira',
                'price' => '3500.00',
                'userprice' => '3500.00',
                'agentprice' => '3500.00',
                'vendorprice' => '3500.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '807',
                'name' => 'SmileVoice ONLY 175 for 90days - 3,600 Naira',
                'price' => '3600.00',
                'userprice' => '3600.00',
                'agentprice' => '3600.00',
                'vendorprice' => '3600.00',
                'day' => '90',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '833',
                'name' => 'Smile MIDI 10GB for 30days - 4,000 Naira',
                'price' => '4000.00',
                'userprice' => '4000.00',
                'agentprice' => '4000.00',
                'vendorprice' => '4000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '834',
                'name' => 'Smile MIDI 13GB for 30days - 5,000 Naira',
                'price' => '5000.00',
                'userprice' => '5000.00',
                'agentprice' => '5000.00',
                'vendorprice' => '5000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '805',
                'name' => 'SmileVoice ONLY 430 for 30days - 5,700 Naira',
                'price' => '5700.00',
                'userprice' => '5700.00',
                'agentprice' => '5700.00',
                'vendorprice' => '5700.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '835',
                'name' => 'Smile MIDI 18GB for 30days - 6,000 Naira',
                'price' => '6000.00',
                'userprice' => '6000.00',
                'agentprice' => '6000.00',
                'vendorprice' => '6000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '836',
                'name' => 'Smile MIDI 20GB for 30days - 7,000 Naira',
                'price' => '7000.00',
                'userprice' => '7000.00',
                'agentprice' => '7000.00',
                'vendorprice' => '7000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '808',
                'name' => 'SmileVoice ONLY 450 for 60days - 7,200 Naira',
                'price' => '7200.00',
                'userprice' => '7200.00',
                'agentprice' => '7200.00',
                'vendorprice' => '7200.00',
                'day' => '60',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '809',
                'name' => 'SmileVoice ONLY 500 for 90days - 9,000 Naira',
                'price' => '9000.00',
                'userprice' => '9000.00',
                'agentprice' => '9000.00',
                'vendorprice' => '9000.00',
                'day' => '90',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '837',
                'name' => 'Smile MIDI 25GB for 30days - 9,000 Naira',
                'price' => '9000.00',
                'userprice' => '9000.00',
                'agentprice' => '9000.00',
                'vendorprice' => '9000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '838',
                'name' => 'Smile MIDI 40GB for 30days - 12,500 Naira',
                'price' => '12500.00',
                'userprice' => '12500.00',
                'agentprice' => '12500.00',
                'vendorprice' => '12500.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '854',
                'name' => 'Smile ANNUAL 20GB for 365days - 14,000 Naira',
                'price' => '14000.00',
                'userprice' => '14000.00',
                'agentprice' => '14000.00',
                'vendorprice' => '14000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '823',
                'name' => 'Smile MAXI Lite for 30days - 15,000 Naira',
                'price' => '15000.00',
                'userprice' => '15000.00',
                'agentprice' => '15000.00',
                'vendorprice' => '15000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '839',
                'name' => 'Smile MIDI 65GB for 30days - 15,000 Naira',
                'price' => '15000.00',
                'userprice' => '15000.00',
                'agentprice' => '15000.00',
                'vendorprice' => '15000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '840',
                'name' => 'Smile MIDI 100GB for 30days - 20,000 Naira',
                'price' => '20000.00',
                'userprice' => '20000.00',
                'agentprice' => '20000.00',
                'vendorprice' => '20000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '841',
                'name' => 'Smile MIDI 130GB for 30days - 25,000 Naira',
                'price' => '25000.00',
                'userprice' => '25000.00',
                'agentprice' => '25000.00',
                'vendorprice' => '25000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '850',
                'name' => 'Smile JUMBO 90GB for 60days - 25,000 Naira',
                'price' => '25000.00',
                'userprice' => '25000.00',
                'agentprice' => '25000.00',
                'vendorprice' => '25000.00',
                'day' => '60',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '824',
                'name' => 'Smile MAXI Essential for 30days - 27,700 Naira',
                'price' => '27700.00',
                'userprice' => '27700.00',
                'agentprice' => '27700.00',
                'vendorprice' => '27700.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '855',
                'name' => 'Smile ANNUAL 50GB for 365days - 29,000 Naira',
                'price' => '29000.00',
                'userprice' => '29000.00',
                'agentprice' => '29000.00',
                'vendorprice' => '29000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '826',
                'name' => 'Smile Maxi Home for 30days - 38,500 Naira',
                'price' => '38500.00',
                'userprice' => '38500.00',
                'agentprice' => '38500.00',
                'vendorprice' => '38500.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '842',
                'name' => 'Smile MIDI 210GB for 30days - 40,000 Naira',
                'price' => '40000.00',
                'userprice' => '40000.00',
                'agentprice' => '40000.00',
                'vendorprice' => '40000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '827',
                'name' => 'Smile MAXI Office for 30days - 45,000 Naira',
                'price' => '45000.00',
                'userprice' => '45000.00',
                'agentprice' => '45000.00',
                'vendorprice' => '45000.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '856',
                'name' => 'Smile ANNUAL 120GB for 365days - 49,500 Naira',
                'price' => '49500.00',
                'userprice' => '49500.00',
                'agentprice' => '49500.00',
                'vendorprice' => '49500.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '851',
                'name' => 'Smile JUMBO 300GB for 90days - 50,000 Naira',
                'price' => '50000.00',
                'userprice' => '50000.00',
                'agentprice' => '50000.00',
                'vendorprice' => '50000.00',
                'day' => '90',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '852',
                'name' => 'Smile JUMBO 350GB for 120days - 60,000 Naira',
                'price' => '60000.00',
                'userprice' => '60000.00',
                'agentprice' => '60000.00',
                'vendorprice' => '60000.00',
                'day' => '120',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '825',
                'name' => 'Smile MAXI DataFlux for 30days - 61,500 Naira',
                'price' => '61500.00',
                'userprice' => '61500.00',
                'agentprice' => '61500.00',
                'vendorprice' => '61500.00',
                'day' => '30',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '853',
                'name' => 'Smile JUMBO 500GB for 180days - 77,000 Naira',
                'price' => '77000.00',
                'userprice' => '77000.00',
                'agentprice' => '77000.00',
                'vendorprice' => '77000.00',
                'day' => '180',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '857',
                'name' => 'Smile ANNUAL 250GB for 365days - 77,000 Naira',
                'price' => '77000.00',
                'userprice' => '77000.00',
                'agentprice' => '77000.00',
                'vendorprice' => '77000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '858',
                'name' => 'Smile ANNUAL 450GB for 365days - 107,000 Naira',
                'price' => '107000.00',
                'userprice' => '107000.00',
                'agentprice' => '107000.00',
                'vendorprice' => '107000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '859',
                'name' => 'Smile ANNUAL 700GB for 365days - 154,000 Naira',
                'price' => '154000.00',
                'userprice' => '154000.00',
                'agentprice' => '154000.00',
                'vendorprice' => '154000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
            [
                'planid' => '860',
                'name' => 'Smile ANNUAL 1TB for 365days - 180,000 Naira',
                'price' => '180000.00',
                'userprice' => '180000.00',
                'agentprice' => '180000.00',
                'vendorprice' => '180000.00',
                'day' => '365',
                'type' => 'SME',
                'datanetwork' => 5,
                'service_type' => 'vtpass',
            ],
        ];

        foreach ($dataplans as $plan) {
            DataPlan::updateOrCreate(
                ['planid' => $plan['planid'], 'datanetwork' => 5], // Unique constraint check
                $plan
            );
        }
    }
}
